language: node_js
cache:
  directories:
    - node_modules
    - build
node_js:
  - "node"
before_install:
  - "npm install -g typescript"
  - "npm install"
  - "tsc -v"
  - "tsc"
script:
  - "npm test"